Repository miraisolutions/Covid19, pull requests merged in 2020-11, with the labels that each got.

#143 Develop
  NEWS.md
  R/mod_map.R
Labels: contribution

#144 2.2.2. release
  R/mod_map.R
Labels: contribution

#145 2.2.2. release
  R/mod_map.R
  R/mod_map_calc_continent.R
Labels: contribution

#147 Feature/135 review hosp data
  NAMESPACE
  NEWS.md
  R/app_server.R
  R/get_data.R
  R/mod_bar_plot_day_contagion.R
  R/mod_caseBoxes.R
  R/mod_compare_nth_cases_plot.R
  R/mod_continent.R
  R/mod_country.R
  R/mod_country_comparison.R
  R/mod_global.R
  R/mod_individual_country.R
  R/mod_lineplots_day_contagion.R
  R/mod_map.R
  R/mod_map_calc_continent.R
  R/mod_plot_log_linear.R
  R/mod_stackedbarplot_status.R
  R/plots.R
  R/utils.R
  README.Rmd
  man-roxygen/ex-country.R
  man-roxygen/ex-individual_country.R
  man-roxygen/ex-map_continent.calc.R
  man-roxygen/ex-mod-area-plot.R
  man-roxygen/ex-mod_stackedbarplot_status.R
  man-roxygen/ex-plot_log_linear.R
  man/aggr_to_cont.Rd
  man/areaplot_hospvars.Rd
  man/areaplot_vars.Rd
  man/case_colors_labs.Rd
  man/dot-case_colors.Rd
  man/dot-current_vars.Rd
  man/dot-hosp_colors.Rd
  man/dot-hosp_vars.Rd
  man/dot-hosp_vars_datahub.Rd
  man/dot-neg_vars.Rd
  man/dot-rate_vars.Rd
  man/dot-tests_colors.Rd
  man/fix_colors.Rd
  man/get_datahub.Rd
  man/message_conf_case.Rd
  man/message_firstday.Rd
  man/message_hosp_data.Rd
  man/message_missing_data.Rd
  man/mod_caseBoxes.Rd
  man/oneM_pop_calc.Rd
  man/plot_all_highlight.Rd
  man/prefix_colors.Rd
  man/time_evol_area_plot.Rd
  man/varsNames.Rd
  tests/testthat/test-get-datahub.R
Labels: contribution

#148 2.2.3 release
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/app_server.R
  R/get_data.R
  R/mod_bar_plot_day_contagion.R
  R/mod_caseBoxes.R
  R/mod_compare_nth_cases_plot.R
  R/mod_continent.R
  R/mod_country.R
  R/mod_country_comparison.R
  R/mod_global.R
  R/mod_individual_country.R
  R/mod_lineplots_day_contagion.R
  R/mod_map.R
  R/mod_map_calc_continent.R
  R/mod_plot_log_linear.R
  R/mod_stackedbarplot_status.R
  R/plots.R
  R/utils.R
  README.Rmd
  man-roxygen/ex-country.R
  man-roxygen/ex-individual_country.R
  man-roxygen/ex-map_continent.calc.R
  man-roxygen/ex-mod-area-plot.R
  man-roxygen/ex-mod_stackedbarplot_status.R
  man-roxygen/ex-plot_log_linear.R
  man/aggr_to_cont.Rd
  man/areaplot_hospvars.Rd
  man/areaplot_vars.Rd
  man/case_colors_labs.Rd
  man/dot-case_colors.Rd
  man/dot-current_vars.Rd
  man/dot-hosp_colors.Rd
  man/dot-hosp_vars.Rd
  man/dot-hosp_vars_datahub.Rd
  man/dot-neg_vars.Rd
  man/dot-rate_vars.Rd
  man/dot-tests_colors.Rd
  man/fix_colors.Rd
  man/get_datahub.Rd
  man/message_conf_case.Rd
  man/message_firstday.Rd
  man/message_hosp_data.Rd
  man/message_missing_data.Rd
  man/mod_caseBoxes.Rd
  man/oneM_pop_calc.Rd
  man/plot_all_highlight.Rd
  man/prefix_colors.Rd
  man/time_evol_area_plot.Rd
  man/varsNames.Rd
  tests/testthat/test-get-datahub.R
Labels: todo

#150 Feature/146 update covid19datahub 2.3.1
  .github/workflows/ci-cd.yml
  NAMESPACE
  NEWS.md
  R/get_data.R
  R/mod_map_calc_continent.R
  man/get_datahub.Rd
  tests/testthat/test-get-datahub.R
Labels: contribution

#152 Fix package version for 2.2.3 release
  DESCRIPTION
  NEWS.md
Labels: release

#151 Setup renv to track and control package dependencies
  .Rbuildignore
  .Rprofile
  .github/workflows/ci-cd.yml
  DESCRIPTION
  deploy/deploy-shinyapps.R
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/renv-setup.R
  renv/settings.dcf
Labels: ci-cd, maintenance

#153 Feature/134 adjust 1 mpop
  NAMESPACE
  NEWS.md
  R/app_server.R
  R/mod_compare_nth_cases_plot.R
  R/mod_continent.R
  R/mod_continent_comparison.R
  R/mod_country.R
  R/mod_country_comparison.R
  R/mod_global.R
  R/mod_growth_death_rate.R
  R/mod_individual_country.R
  R/mod_lineplots_day_contagion.R
  R/mod_map_calc_continent.R
  R/mod_scatterplot.R
  R/plots.R
  R/utils.R
  man-roxygen/ex-country-comparison.R
  man-roxygen/ex-mod_compare_nth_cases_plot.R
  man/case_colors_labs.Rd
  man/choice_nthcases_plot.Rd
  man/dot-rate_vars.Rd
  man/fix_colors.Rd
  man/prefix_colors.Rd
  man/prefix_var.Rd
  man/vars_nthcases_plot.Rd
Labels: contribution

#154 2.2.4 release
  .Rbuildignore
  .Rprofile
  .github/workflows/ci-cd.yml
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/app_server.R
  R/get_data.R
  R/mod_compare_nth_cases_plot.R
  R/mod_continent.R
  R/mod_continent_comparison.R
  R/mod_country.R
  R/mod_country_comparison.R
  R/mod_global.R
  R/mod_growth_death_rate.R
  R/mod_individual_country.R
  R/mod_lineplots_day_contagion.R
  R/mod_map_calc_continent.R
  R/mod_scatterplot.R
  R/plots.R
  R/utils.R
  deploy/deploy-shinyapps.R
  man-roxygen/ex-country-comparison.R
  man-roxygen/ex-mod_compare_nth_cases_plot.R
  man-roxygen/ex-mod_scatterplot.R
  man/case_colors_labs.Rd
  man/choice_nthcases_plot.Rd
  man/dot-rate_vars.Rd
  man/fix_colors.Rd
  man/get_datahub.Rd
  man/prefix_colors.Rd
  man/prefix_var.Rd
  man/vars_nthcases_plot.Rd
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/renv-setup.R
  renv/settings.dcf
  tests/testthat/test-get-datahub.R
Labels: release
